### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by bosonno** [jjethwa/icinga2#10]
INFO[0006] The command [/bin/sh -c mv /tmp/master/icingaweb2-master/modules/monitoring/* /etc/icingaweb2/modules/monitoring/] returned a non-zero code: 1

**Comment by jjethwa** [comment]
Hi @bosonno 

Sorry about that.  Looks like the latest icingaweb2 checkout from git has changes a few things.  I'll investigate and update this repo.  Thanks :)

**Comment by jjethwa** [comment]
Hi @bosonno 

It looks like the latest commit on icingaweb2 breaks some functionality (see: https://github.com/Icinga/icingaweb2/commit/a817d9070e966ecc692ca67f311ee7f2a2cca12f )  I've modified the Dockerfile to use the latest tagged version instead of pulling from master to make sure we always get a working version instead.

If this fixes your issue, please close it.  Thanks :)
