### ISSUE TITLE
Question: Reload configuration of icinga2

### ISSUE THREAD

**Issue by christophlsa** [jjethwa/icinga2#154]
Hi,

I just want to ask you what would be the best way to reload the configuration of icinga2 (hosts, services etc). Right now I restart the docker container but I think this is not the best way. How you do this?

Sorry if it is the wrong place here but I don't know what is the right place.

**Comment by bebehei** [comment]
I'd recommend: Externalise your MySQL host. It'll reduce container reboot times dramatically.

But before we had been able to have an external MySQL host, I had a small script on my host:

```
#!/bin/bash
# i2docker-reload-master
CONTAINERNAME=icinga2_icinga2_1

   docker exec -t $CONTAINERNAME icinga2 daemon --validate \
&& docker exec -t $CONTAINERNAME killall -v -HUP icinga2
```

This does basically everything, because:

- You don't want to restart the service, if your config is actually broken.
- The HUP signal is independent of the container architecture, it's just saying it directly to the `icinga2` process to reload it.
