### ISSUE TITLE
always modify apiuser "icinga2-director"

### ISSUE THREAD

**Issue by artemicruz** [jjethwa/icinga2#166]
Whenever the dockericingaweb2_icinga2_1 container is started in "icinga director"> "activity log" Deploy 1 pending changes.
[admin] modify apiuser "icinga2-director"
"icinga2-director" has been modified
zones.d / master / apiusers.conf

**Comment by bebehei** [comment]
Sorry, I don't get you point. Could you please clarify what you mean?

**Comment by artemicruz** [comment]
every time icinga container starts, a new deploy pending changes appears.

<a href="https://ibb.co/hPe7cA"><img src="https://preview.ibb.co/mF80xA/Captura-restart.jpg" alt="Captura-restart" border="0"></a>

**Comment by jjethwa** [comment]
@artemicruz  The container regenerates certain configurations during startup. Is this causing an issue for you?

**Comment by tinuva** [comment]
Is there a way to disable some (or specifically this one) of the configurations that are regenerated on each startup?
I think its annoying when you have to see there is a change waiting to deploy every time it is restarted.

**Comment by jjethwa** [comment]
Hi @tinuva 

Unfortunately, I don't believe it's possible at this time since starting a container generates a new random hostname.  This requires us to regenerate some of the configs in order to match the new name.  I'll check to see if there are underlying changes in Docker that might help.

**Comment by tinuva** [comment]
I think I found the answer/solution to problem/issue. I don't get this anymore after setting the following environment variables in my docker-compose file for this container:

      ICINGA2_FEATURE_DIRECTOR_USER=icinga2-director
      ICINGA2_FEATURE_DIRECTOR_PASS=<anyPassWord>

Now when the container restarts, I don't get a new deployment. Probably because I am specifying a password, it doesn't generate a random password anymore.

Would be great if these 2 could be added to the "Environment variables Reference" section that shows on https://hub.docker.com/r/jordan/icinga2

**Comment by jjethwa** [comment]
Hi @tinuva 

Nice find!  If you want to submit a PR for the README,md that would be great so you can get credit 😄

**Comment by tinuva** [comment]
PR submitted.

**Comment by jjethwa** [comment]
Thank you , @tinuva  😄
