### ISSUE TITLE
Adding Vsphere Module

### ISSUE THREAD

**Issue by kratzersmz** [jjethwa/icinga2#270]
Is there a way to add https://icinga.com/docs/icinga-module-for-vsphere/latest/doc/01-Installation/ Module? How can i do that and run docker-compose with this module packed....

Greets

**Comment by jjethwa** [comment]
Hi @kratzersmz 

I haven't used this module, but from reviewing the link you provided, you should be able to add it using a volume with the downloaded module source and creating a custom run script added via another volume at /opt/custom_run

The custom run script will need to include installation of the perl modules need as well.  The only difference with the instructions provided is that, since this is running in a container, there is no systemd, but supervisor is available, so you would also need to create a supervisor conf file for the vsphere service.

**Comment by kratzersmz** [comment]
great, thanks for your help and info, will gonna try it

**Comment by jjethwa** [comment]
No problem, @kratzersmz 

If you run into any problems, let me know and I can try to help 😃

**Comment by skupjoe** [comment]
@kratzersmz I've added it and it works fine using the custom run scripts.

I also agree it should probably not be added as part of the base image, but rather left to users to add in via custom run scripts

**Comment by MarcusCaepio** [comment]
> @kratzersmz I've added it and it works fine using the custom run scripts.
> 
> I also agree it should probably not be added as part of the base image, but rather left to users to add in via custom run scripts

@skupjoe Could you share a little how-to add the module? :) 
Thanks in advance
